site_name: undercover-ftw
site_description: "Main documentation for undercover-ftw project"
repo_url: https://github.com/xgeeks-geekathon/undercover-ftw.git
edit_uri: edit/master/docs

# plugins:
#   - techdocs-core

# For sidebar navigation
nav:
  - Getting Started: "index.md"
